{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myproperty.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "myproperty.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
{{- end }}
