apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backend-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myproperty.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.backend.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.backend.storage.size }}
