{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myproperty.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  type: ClusterIP
  selector:
    {{- include "myproperty.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
      protocol: TCP
{{- end }}
