{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myproperty.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  type: ClusterIP
  selector:
    {{- include "myproperty.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
{{- end }}
