# Managed Postgres 16. Same region as the DOKS cluster so both land in fra1's
# default VPC — backend pods reach the DB via DO's private network without
# adding the cluster's egress to the DB's trusted sources list.

resource "digitalocean_database_cluster" "myproperty" {
  name       = var.db_cluster_name
  engine     = "pg"
  version    = var.db_engine_version
  size       = var.db_size
  region     = var.region
  node_count = 1
}

# Application database (separate from the auto-created `defaultdb` and `doadmin`-owned schema).
resource "digitalocean_database_db" "myproperty" {
  cluster_id = digitalocean_database_cluster.myproperty.id
  name       = var.db_name
}

# Non-admin app user. Receives a random password generated by DO; the password
# is retrievable from `digitalocean_database_user.myproperty.password` (sensitive).
resource "digitalocean_database_user" "myproperty" {
  cluster_id = digitalocean_database_cluster.myproperty.id
  name       = var.db_user
}

# Firewall: only the DOKS cluster can reach the DB. Without this, the DB is
# wide open within the VPC; with this, the DB rejects connections from any
# other source. Cluster-scoped trusted source is the DO-recommended pattern.
resource "digitalocean_database_firewall" "myproperty" {
  cluster_id = digitalocean_database_cluster.myproperty.id

  rule {
    type  = "k8s"
    value = digitalocean_kubernetes_cluster.myproperty.id
  }
}
