{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "myproperty.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    {{ include "myproperty.certIssuerAnnotation" . }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
  {{- include "myproperty.tlsHosts" . | nindent 8 }}
secretName: {{ .Values.ingress.tls.secretName }}
rules:
  - host: {{ .Values.hosts.app }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                name: http
  {{- end }}
